---
title: "teaching"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
library(fmsb)
library(scales)
library(RColorBrewer)
#library(hrbrthemes)
library(GGally)
library(viridis)
```


```{r eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
data <- as.data.frame(matrix(c(78, 80, 67, 72, 70, 67, 72, 74, 72, 78), ncol=10))

colnames(data) <- c("Inclusiveness" , "Support" , "Feedback" , "Level of challenge" , "Quality of materials", "Instructor communication", "Organization", "Relevance", "Assignments", "Accessibility")

# To use the fmsb package, I have to add 2 lines to the dataframe: the max and min of each topic to show on the plot!
data <- rbind(rep(100,10) , rep(0,10) , data)

radarchart(data, axistype=1, 
  #custom polygon
  pcol=rgb(0.2,0.5,0.5,0.9), pfcol=rgb(0.2,0.5,0.5,0.5), plwd=4,
  #custom the grid
  cglcol="grey", cglty=1, axislabcol="grey", cglwd=0.8,
  #custom labels
  vlcex=1, 
  seg=4 #caxislabels=seq(0,1,4), 
  )

mtext(side = 3, line = 2.5, at = 0, cex = 1, "Student Experience Survey: EC370 Money & Banking, Fall 2019", font = 2)
mtext(side = 3, line = 1, at = 0, cex = 1, "... is beneficial to my learning", col = '#666664')

legend(x=.65, y=-1.1, legend = "% of responses", bty = "n",  pch=20, col=rgb(0.2,0.5,0.5,0.9), text.col = '#666664', cex=1, pt.cex=3)
```

